#!/usr/bin/env python

import json
import glob
import sys

data = json.loads(sys.stdin.read())

data = [{
    "timestamp": d['timestamp'],
    "author": d['author'],
    "body": d['body'] if 'body' in d else ""
} for d in data]

sys.stdout.write(json.dumps(data))
